### ISSUE TITLE
How to use this project with cuda stream?

### ISSUE THREAD

**Issue by cracy3m** [pierrepaleo/PDWT#6]
Hi there,

Is it possible to set cuda stream explicit when use this library? Which interface function should I invoke?

**Comment by pierrepaleo** [comment]
Hi @cracy3m,

Sorry, this library does not have anything to set/switch streams. 

To be honest I haven't played with streams much, so any PR on the subject would be welcome.

**Comment by cracy3m** [comment]
> 
Thanks to reply!
I have no time to extend stream feature on this project, so I just use cufft to do 1D DWT stuff with stream.
Any way, thank you very much!
